### ISSUE TITLE
error on apply

### ISSUE THREAD

**Issue by ralyodio** [IggsGrey/linkedin-easy-apply-bot#9]
```
$ pnpm run apply 

> scripts@1.0.0 apply /home/ettinger/src/profullstack.com/linkedin-easy-apply-bot
> ts-node ./scripts/apply.ts SUBMIT

Error: No element found for selector: #session_key
    at assert (/home/ettinger/src/profullstack.com/linkedin-easy-apply-bot/node_modules/.pnpm/puppeteer-core@19.11.1_typescript@5.5.4/node_modules/puppeteer-core/src/util/assert.ts:29:11)
    at IsolatedWorld.type (/home/ettinger/src/profullstack.com/linkedin-easy-apply-bot/node_modules/.pnpm/puppeteer-core@19.11.1_typescript@5.5.4/node_modules/puppeteer-core/src/common/IsolatedWorld.ts:351:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async login (/home/ettinger/src/profullstack.com/linkedin-easy-apply-bot/login/index.ts:18:3)
    at async /home/ettinger/src/profullstack.com/linkedin-easy-apply-bot/scripts/apply.ts:46:3
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by IggsGrey** [comment]
Hey @ralyodio  , haven't run this in a while, I'll have to do a test run when I get home and see what happens.

**Comment by ralyodio** [comment]
ok thanks. let me know if you fix it. would be cool!

**Comment by IggsGrey** [comment]
@ralyodio 

https://github.com/IggsGrey/linkedin-easy-apply-bot/pull/11

**Comment by IggsGrey** [comment]
let me know if this fixes the bug for you

**Comment by ralyodio** [comment]
```
n) ✗ 
$ pnpm run apply  

> scripts@1.0.0 apply /home/ettinger/src/profullstack.com/linkedin-easy-apply-bot
> ts-node ./scripts/apply.ts SUBMIT

[8/2/2024, 13:14:36] Logged in to LinkedIn
press enter to pause the program
Error: No element found for selector: input[id*="jobs-search-box-keyword-id"]
    at assert (/home/ettinger/src/profullstack.com/linkedin-easy-apply-bot/node_modules/.pnpm/puppeteer-core@19.11.1_typescript@5.5.4/node_modules/puppeteer-core/src/util/assert.ts:29:11)
    at IsolatedWorld.type (/home/ettinger/src/profullstack.com/linkedin-easy-apply-bot/node_modules/.pnpm/puppeteer-core@19.11.1_typescript@5.5.4/node_modules/puppeteer-core/src/common/IsolatedWorld.ts:351:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getJobSearchMetadata (/home/ettinger/src/profullstack.com/linkedin-easy-apply-bot/fetch/fetchJobLinksUser.ts:17:3)
    at async fetchJobLinksUser (/home/ettinger/src/profullstack.com/linkedin-easy-apply-bot/fetch/fetchJobLinksUser.ts:62:39)
    at async /home/ettinger/src/profullstack.com/linkedin-easy-apply-bot/scripts/apply.ts:71:45
 ELIFECYCLE  Command failed with exit code 1.
 ```

**Comment by IggsGrey** [comment]
@ralyodio   let's pick this up over here instead https://github.com/IggsGrey/linkedin-easy-apply-bot/issues/12
